apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: viallins-api
  description: Villains API is a RESTful API that manages villains.
  tags:
    - rust
    - data
  links:
    - url: https://github.com/returngis/tour-of-villains-rust-api
      title: Source Code
      icon: github
    - url: https://api.villains.com
      title: Production
      icon: globe
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: openai
  lifecycle: production
  owner: guests
  system: tour-of-heroes
  dependsOn: ['resource:villains-db']
  apiConsumedBy: ['component:www-villains']

    